### ISSUE TITLE
This library does not work with Play Framework

### ISSUE THREAD

**Issue by slisaasquatch** [recurly/recurly-client-java#96]
**Describe the bug**

Given a [Play](https://www.playframework.com/) 2.8 project, simply including this library as a dependency without using it will cause the following error:

```
 Exception in thread "main" java.lang.NoSuchMethodError: com.google.inject.Binder.disableCircularProxies()V
 	at play.api.inject.guice.BinderOption$DisableCircularProxies$$anonfun$$lessinit$greater$1.apply(GuiceInjectorBuilder.scala:402)
 	at play.api.inject.guice.BinderOption$DisableCircularProxies$$anonfun$$lessinit$greater$1.apply(GuiceInjectorBuilder.scala:402)
 	at play.api.inject.guice.BinderOption.apply(GuiceInjectorBuilder.scala:397)
 	at play.api.inject.guice.GuiceableModuleConversions$$anon$4.$anonfun$configure$1(GuiceInjectorBuilder.scala:373)
 	at play.api.inject.guice.GuiceableModuleConversions$$anon$4.$anonfun$configure$1$adapted(GuiceInjectorBuilder.scala:373)
 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
 	at play.api.inject.guice.GuiceableModuleConversions$$anon$4.configure(GuiceInjectorBuilder.scala:373)
 	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
 	at com.google.inject.spi.Elements.getElements(Elements.java:101)
 	at com.google.inject.spi.Elements.getElements(Elements.java:92)
 	at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:152)
 	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
 	at com.google.inject.spi.Elements.getElements(Elements.java:101)
 	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:116)
 	at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:100)
 	at com.google.inject.Guice.createInjector(Guice.java:95)
 	at com.google.inject.Guice.createInjector(Guice.java:83)
 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
 	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
 	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:54)
 	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:30)
 	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

Looks like a Guice version conflict, but this library doesn't use Guice, so maybe it's a transitive dependency?

**To Reproduce**

Create a Play project, include this dependency in `build.sbt`, and `sbt run`.

**Expected behavior**

I would expect this library to work with Play.

**Your Environment**

- Which version of this library are you using?
3.5.0
- Which version of the language are you using?
Java 1.8.0_232

**Comment by bhelx** [comment]
Glad to see you are trying out our V3 library @slisaasquatch ! I'll try to reproduce the problem.

**Comment by bhelx** [comment]
I was able to repro. Another dev was not. We're digging into to understand. I can't seem to find where guice would be coming from either.

**Comment by bhelx** [comment]
@slisaasquatch The only differences b/w myself and the dev who cannot repro are sbt versions. What do you get with: `sbt --version`?

**Comment by slisaasquatch** [comment]
1.3.4

**Comment by bhelx** [comment]
That's the one I'm using. The dev without experiencing the problem is on `1.3.10`. Any way you can try upgrading SBT?

**Comment by slisaasquatch** [comment]
Sure, but I'll probably have to put this on hold and try it in a couple of days.

**Comment by bhelx** [comment]
No rush! It seems environmental because I can't repro this in any other context.

**Comment by slisaasquatch** [comment]
Looks like that's it. SBT 1.3.10 works. I'll close the ticket.
